[package]
name = "ping-pong-test-meta"
version = "0.0.0"
authors = ["Bruda Claudiu-Marcel <claudiu725@yahoo.com>"]
edition = "2021"
publish = false

[dependencies.ping-pong-test]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.57.0"
default-features = false
